pipeline {
    agent { label 'server1' }
    stages{
        stage('build'){
            steps{
                echo "This is build stage"
            }
        }
        stage('test'){
            steps{
                echo "this is test stage"
            }
        }
        stage('deploy'){
            steps{
                echo "This is deploy stage"
            }
        }
    }
}
